### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined 

### ISSUE THREAD

**Issue by luizaugustocs** [entria/font-generator#7]
Hey guys,

Great job, this library really helped our project. 

But, we had a problem after installing it.
We had the same bug reported on #1 after a fresh install.

Patching the pull request change manually solved the problem.

**Comment by sibelius** [comment]
which pull request?

should we release a new version?

master is good?

**Comment by luizaugustocs** [comment]
Pull Request #6.

I just did a `npm i -g @entria/font-generator` and got the bug, searching on the issues I found the issue #1 and did the same patch to the file on `~/.nvm/versions/node/v9.9.0/lib/node_modules/@entria/font-generator/lib/runCLI.js:141`.

I think a new release would fix this.

**Comment by sibelius** [comment]
can u check on `1.0.1` ?

**Comment by luizaugustocs** [comment]
Worked, thanks.
